// scripts/codegen-codes.ts
//
// Regenerates `src/codes.ts` from the bundled dataset under `src/data/`.
//
// Usage:
//   npm run codegen          # write src/codes.ts in place
//   npm run codegen:check    # exit 1 if src/codes.ts is out of sync (CI)

import * as fs from "node:fs";
import * as path from "node:path";
import { currencies } from "../src/data";

const HEADER = `// AUTO-GENERATED — do not edit by hand. Run \`npm run codegen\` to regenerate.
// Source of truth: src/data/{fiat,crypto,historical}.ts.
// Drift is enforced in CI via \`npm run codegen:check\`.

/**
 * Strict literal union of every code shipped in the bundled dataset.
 *
 * Codes are uppercase ISO 4217 alpha-3 (for fiat and historical) or the
 * commonly used ticker (for crypto). The union is regenerated by
 * \`scripts/codegen-codes.ts\`; if you add or remove a record under
 * \`src/data/\`, run \`npm run codegen\` so this file stays in sync.
 */
`;

function build(): string {
  const codes = Array.from(new Set(currencies.map((c) => c.code))).sort();
  const union = codes.map((c) => `"${c}"`).join(" | ");
  return `${HEADER}export type CurrencyCode = ${union};\n`;
}

function main(): void {
  const outFile = path.resolve(__dirname, "..", "src", "codes.ts");
  const generated = build();
  const check = process.argv.includes("--check");

  if (check) {
    const existing = fs.existsSync(outFile)
      ? fs.readFileSync(outFile, "utf8")
      : "";
    if (existing !== generated) {
      console.error(
        "codegen-codes: src/codes.ts is out of sync with the dataset.",
      );
      console.error("Run `npm run codegen` to fix.");
      process.exit(1);
    }
    console.log(
      `codegen-codes: src/codes.ts is up to date (${currencies.length} records).`,
    );
    return;
  }

  fs.writeFileSync(outFile, generated);
  console.log(
    `codegen-codes: wrote src/codes.ts with ${currencies.length} records.`,
  );
}

main();
