// AUTO-GENERATED — do not edit by hand. Run `npm run codegen` to regenerate.
// Source of truth: src/data/{fiat,crypto,historical}.ts.
// Drift is enforced in CI via `npm run codegen:check`.

/**
 * Strict literal union of every code shipped in the bundled dataset.
 *
 * Codes are uppercase ISO 4217 alpha-3 (for fiat and historical) or the
 * commonly used ticker (for crypto). The union is regenerated by
 * `scripts/codegen-codes.ts`; if you add or remove a record under
 * `src/data/`, run `npm run codegen` so this file stays in sync.
 */
export type CurrencyCode = "AAVE" | "ADA" | "AED" | "AFA" | "AFN" | "ALGO" | "ALL" | "AMD" | "AOA" | "AOR" | "APT" | "ARB" | "ARS" | "ATOM" | "ATS" | "AUD" | "AVAX" | "AWG" | "AXS" | "AZN" | "BAM" | "BBD" | "BCH" | "BDT" | "BEF" | "BGL" | "BGN" | "BHD" | "BIF" | "BMD" | "BNB" | "BND" | "BOB" | "BRL" | "BSD" | "BTC" | "BTN" | "BWP" | "BYN" | "BYR" | "BZD" | "CAD" | "CDF" | "CHF" | "CLP" | "CNY" | "COP" | "CRC" | "CRO" | "CUP" | "CVE" | "CYP" | "CZK" | "DAI" | "DEM" | "DJF" | "DKK" | "DOGE" | "DOP" | "DOT" | "DZD" | "ECU" | "EEK" | "EGLD" | "EGP" | "ERN" | "ESP" | "ETB" | "ETC" | "ETH" | "EUR" | "FIL" | "FIM" | "FJD" | "FKP" | "FLOW" | "FRF" | "GBP" | "GBX" | "GEL" | "GHS" | "GIP" | "GMD" | "GNF" | "GRD" | "GRT" | "GTQ" | "GYD" | "HBAR" | "HKD" | "HNL" | "HRK" | "HTG" | "HUF" | "ICP" | "IDR" | "IEP" | "ILS" | "INJ" | "INR" | "IQD" | "IRR" | "ISK" | "ITL" | "JMD" | "JOD" | "JPY" | "KAS" | "KES" | "KGS" | "KHR" | "KMF" | "KPW" | "KRW" | "KWD" | "KYD" | "KZT" | "LAK" | "LBP" | "LINK" | "LKR" | "LRD" | "LSL" | "LTC" | "LTL" | "LUF" | "LVL" | "LYD" | "MAD" | "MATIC" | "MDL" | "MGA" | "MKD" | "MKR" | "MMK" | "MNT" | "MOP" | "MRU" | "MTL" | "MUR" | "MVR" | "MWK" | "MXN" | "MYR" | "MZM" | "MZN" | "NAD" | "NEAR" | "NGN" | "NIO" | "NLG" | "NOK" | "NPR" | "NZD" | "OKB" | "OMR" | "PAB" | "PEN" | "PGK" | "PHP" | "PKR" | "PLN" | "PTE" | "PYG" | "QAR" | "QNT" | "ROL" | "RON" | "RSD" | "RUB" | "RUNE" | "RWF" | "SAND" | "SAR" | "SBD" | "SCR" | "SDG" | "SEK" | "SGD" | "SHIB" | "SHP" | "SIT" | "SKK" | "SLE" | "SOL" | "SOS" | "SRD" | "SSP" | "STN" | "STX" | "SUR" | "SVC" | "SYP" | "SZL" | "THB" | "THETA" | "TJS" | "TMT" | "TND" | "TON" | "TOP" | "TRL" | "TRX" | "TRY" | "TTD" | "TUSD" | "TWD" | "TZS" | "UAH" | "UGX" | "UNI" | "USD" | "USDC" | "USDT" | "UYU" | "UZS" | "VES" | "VET" | "VND" | "VUV" | "WBTC" | "WST" | "XAF" | "XCD" | "XCG" | "XLM" | "XMR" | "XOF" | "XPF" | "XRP" | "XTZ" | "YER" | "YUM" | "ZAR" | "ZMW" | "ZWD" | "ZWG";
